version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Explicitly set the version of Python and its requirements
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - git clone -b main --depth=1 https://github.com/weaviate/weaviate-agents-python-client.git docs/weaviate-agents-python-client

python:
  install:
  - requirements: requirements-devel.txt