version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Explicitly set the version of Python and its requirements
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

python:
  install:
  - requirements: requirements-devel.txt