version: '3.4'
services:
  weaviate:
    container_name: "weaviate"
    restart: always
    image: semitechnologies/weaviate:1.28.2
    ports:
      - "8080:8080"
      - "0.0.0.0:50051:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      LOG_LEVEL: 'debug'
    volumes:
      - weaviate_data:/var/lib/weaviate
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  weaviate_data:
    name: "weaviate_data"
