[pytest]
addopts = -m 'not profiling' --benchmark-skip -l --capture=sys --max-worker-restart=3
markers =
    profiling: marks tests that can be profiled
    timeout: marks tests with a custom timeout in seconds (default: 300)
asyncio_default_fixture_loop_scope = function