from typing import Optional, Sequence

from weaviate.collections.tenants.types import (
    TenantCreateInputType,
    TenantInputType,
    TenantOutputType,
    TenantUpdateInputType,
)
from weaviate.connect.v4 import ConnectionAsync

from .executor import _TenantsExecutor

class _TenantsAsync(_TenantsExecutor[ConnectionAsync]):
    async def create(
        self, tenants: TenantCreateInputType | Sequence[TenantCreateInputType]
    ) -> None: ...
    async def remove(self, tenants: TenantInputType | Sequence[TenantInputType]) -> None: ...
    async def get(self) -> dict[str, TenantOutputType]: ...
    async def get_by_names(
        self, tenants: Sequence[TenantInputType]
    ) -> dict[str, TenantOutputType]: ...
    async def get_by_name(self, tenant: TenantInputType) -> Optional[TenantOutputType]: ...
    async def update(
        self, tenants: TenantUpdateInputType | Sequence[TenantUpdateInputType]
    ) -> None: ...
    async def exists(self, tenant: TenantInputType) -> bool: ...
    async def activate(self, tenant: TenantInputType | Sequence[TenantInputType]) -> None: ...
    async def deactivate(self, tenant: TenantInputType | Sequence[TenantInputType]) -> None: ...
    async def offload(self, tenant: TenantInputType | Sequence[TenantInputType]) -> None: ...
