# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_get.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10search_get.proto\x12\x0cweaviategrpc\"\x0f\n\rSearchRequest\"\r\n\x0bSearchReplyBi\n\x19io.weaviate.grpc.protocolB\x16WeaviateProtoSearchGetZ4github.com/weaviate/weaviate/grpc/generated;protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_get_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031io.weaviate.grpc.protocolB\026WeaviateProtoSearchGetZ4github.com/weaviate/weaviate/grpc/generated;protocol'
  _globals['_SEARCHREQUEST']._serialized_start=34
  _globals['_SEARCHREQUEST']._serialized_end=49
  _globals['_SEARCHREPLY']._serialized_start=51
  _globals['_SEARCHREPLY']._serialized_end=64
# @@protoc_insertion_point(module_scope)
