# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/aggregate.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 27, 2, "", "v1/aggregate.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12v1/aggregate.proto\x12\x0bweaviate.v1"v\n\x10\x41ggregateRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x12\n\nmeta_count\x18\x14 \x01(\x08\x12\x19\n\x0cobject_limit\x18\x1e \x01(\rH\x00\x88\x01\x01\x12\x0e\n\x06tenant\x18\n \x01(\tB\x0f\n\r_object_limit"L\n\x0e\x41ggregateReply\x12\x0c\n\x04took\x18\x01 \x01(\x02\x12,\n\x06result\x18\x02 \x01(\x0b\x32\x1c.weaviate.v1.AggregateResult"D\n\x0f\x41ggregateResult\x12\x31\n\x06groups\x18\x01 \x03(\x0b\x32!.weaviate.v1.AggregateGroupResult"%\n\x14\x41ggregateGroupResult\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\x42s\n#io.weaviate.client.grpc.protocol.v1B\x16WeaviateProtoAggregateZ4github.com/weaviate/weaviate/grpc/generated;protocolb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.aggregate_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = (
        b"\n#io.weaviate.client.grpc.protocol.v1B\026WeaviateProtoAggregateZ4github.com/weaviate/weaviate/grpc/generated;protocol"
    )
    _globals["_AGGREGATEREQUEST"]._serialized_start = 35
    _globals["_AGGREGATEREQUEST"]._serialized_end = 153
    _globals["_AGGREGATEREPLY"]._serialized_start = 155
    _globals["_AGGREGATEREPLY"]._serialized_end = 231
    _globals["_AGGREGATERESULT"]._serialized_start = 233
    _globals["_AGGREGATERESULT"]._serialized_end = 301
    _globals["_AGGREGATEGROUPRESULT"]._serialized_start = 303
    _globals["_AGGREGATEGROUPRESULT"]._serialized_end = 340
# @@protoc_insertion_point(module_scope)
