# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/aggregate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from weaviate.proto.v1 import base_pb2 as v1_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12v1/aggregate.proto\x12\x0bweaviate.v1\x1a\rv1/base.proto"Q\n\x10\x41ggregateRequest\x12\x12\n\ncollection\x18\x01 \x01(\t\x12\x0e\n\x06tenant\x18\n \x01(\t\x12\x19\n\x11number_of_objects\x18\x14 \x01(\x08"M\n\x0e\x41ggregateReply\x12\x0c\n\x04took\x18\x01 \x01(\x02\x12-\n\x07results\x18\x02 \x03(\x0b\x32\x1c.weaviate.v1.AggregateResult",\n\x0f\x41ggregateResult\x12\x19\n\x11number_of_objects\x18\x01 \x01(\x03\x42s\n#io.weaviate.client.grpc.protocol.v1B\x16WeaviateProtoAggregateZ4github.com/weaviate/weaviate/grpc/generated;protocolb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.aggregate_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n#io.weaviate.client.grpc.protocol.v1B\026WeaviateProtoAggregateZ4github.com/weaviate/weaviate/grpc/generated;protocol"
    _globals["_AGGREGATEREQUEST"]._serialized_start = 50
    _globals["_AGGREGATEREQUEST"]._serialized_end = 131
    _globals["_AGGREGATEREPLY"]._serialized_start = 133
    _globals["_AGGREGATEREPLY"]._serialized_end = 210
    _globals["_AGGREGATERESULT"]._serialized_start = 212
    _globals["_AGGREGATERESULT"]._serialized_end = 256
# @@protoc_insertion_point(module_scope)
