# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v1/struct.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fv1/struct.proto\x12\x0bweaviate.v1"|\n\x06Struct\x12/\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1f.weaviate.v1.Struct.FieldsEntry\x1a\x41\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.weaviate.v1.Value:\x02\x38\x01"\xf1\x01\n\x05Value\x12\x16\n\x0cnumber_value\x18\x02 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12+\n\x0cobject_value\x18\x05 \x01(\x0b\x32\x13.weaviate.v1.StructH\x00\x12,\n\nlist_value\x18\x06 \x01(\x0b\x32\x16.weaviate.v1.ListValueH\x00\x12\x14\n\ndate_value\x18\x07 \x01(\tH\x00\x12\x14\n\nuuid_value\x18\x08 \x01(\tH\x00\x12\x13\n\tint_value\x18\t \x01(\x03H\x00\x42\x06\n\x04kind"/\n\tListValue\x12"\n\x06values\x18\x01 \x03(\x0b\x32\x12.weaviate.v1.ValueB\x84\x01\n\x13\x63om.google.protobufB\x0bStructProtoP\x01Z4github.com/weaviate/weaviate/grpc/generated;protocol\xf8\x01\x01\xa2\x02\x03GPB\xaa\x02\x1eGoogle.Protobuf.WellKnownTypesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v1.struct_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\023com.google.protobufB\013StructProtoP\001Z4github.com/weaviate/weaviate/grpc/generated;protocol\370\001\001\242\002\003GPB\252\002\036Google.Protobuf.WellKnownTypes"
    _STRUCT_FIELDSENTRY._options = None
    _STRUCT_FIELDSENTRY._serialized_options = b"8\001"
    _globals["_STRUCT"]._serialized_start = 32
    _globals["_STRUCT"]._serialized_end = 156
    _globals["_STRUCT_FIELDSENTRY"]._serialized_start = 91
    _globals["_STRUCT_FIELDSENTRY"]._serialized_end = 156
    _globals["_VALUE"]._serialized_start = 159
    _globals["_VALUE"]._serialized_end = 400
    _globals["_LISTVALUE"]._serialized_start = 402
    _globals["_LISTVALUE"]._serialized_end = 449
# @@protoc_insertion_point(module_scope)
