from typing import Dict, List, Optional, Sequence, Union

from weaviate.connect.v4 import ConnectionAsync
from weaviate.rbac.models import (
    PermissionsOutputType,
    PermissionsInputType,
    Role,
)
from weaviate.rbac.base import _RolesBase

class _RolesAsync(_RolesBase[ConnectionAsync]):
    async def list_all(self) -> Dict[str, Role]: ...
    async def get(self, role_name: str) -> Optional[Role]: ...
    async def get_assigned_user_ids(self, role_name: str) -> List[str]: ...
    async def get_assigned_db_user_ids(self, role_name: str) -> List[str]: ...
    async def get_assigned_oidc_user_ids(self, role_name: str) -> List[str]: ...
    async def delete(self, role_name: str) -> None: ...
    async def create(self, *, role_name: str, permissions: PermissionsInputType) -> Role: ...
    async def exists(self, role_name: str) -> bool: ...
    async def add_permissions(
        self, *, permissions: PermissionsInputType, role_name: str
    ) -> None: ...
    async def remove_permissions(
        self, *, permissions: PermissionsInputType, role_name: str
    ) -> None: ...
    async def has_permissions(
        self,
        *,
        permissions: Union[
            PermissionsInputType, PermissionsOutputType, Sequence[PermissionsOutputType]
        ],
        role: str
    ) -> bool: ...
