---
version: '3.4'
services:
  weaviate_openai:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8086'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.19.2
    ports:
      - 8086:8086
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,generative-openai'
      CLUSTER_HOSTNAME: 'node1'