---
version: '3.4'
services:
  weaviate-rbac:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8085'
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:${WEAVIATE_VERSION}
    ports:
      - 8092:8085
      - "50063:50051"
    restart: on-failure:0
    environment:
      ENABLE_MODULES: "generative-dummy,reranker-dummy"
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: "existing-key"
      AUTHENTICATION_APIKEY_USERS: "existing-user"
      AUTHORIZATION_ADMIN_USERS: "existing-user"
      PERSISTENCE_DATA_PATH: "./data-weaviate-0"
      CLUSTER_IN_LOCALHOST: "true"
      CLUSTER_GOSSIP_BIND_PORT: "7100"
      CLUSTER_DATA_BIND_PORT: "7101"
      RAFT_BOOTSTRAP_EXPECT: "1"
      AUTHORIZATION_ENABLE_RBAC: "true"
...
