# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0/batch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v0 from . import base_pb2 as v0_dot_base__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ev0/batch.proto\x12\x0cweaviategrpc\x1a\rv0/base.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x97\x01\n\x13\x42\x61tchObjectsRequest\x12*\n\x07objects\x18\x01 \x03(\x0b\x32\x19.weaviategrpc.BatchObject\x12>\n\x11\x63onsistency_level\x18\x02 \x01(\x0e\x32\x1e.weaviategrpc.ConsistencyLevelH\x00\x88\x01\x01\x42\x14\n\x12_consistency_level\"\x8b\x06\n\x0b\x42\x61tchObject\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\x38\n\nproperties\x18\x03 \x01(\x0b\x32$.weaviategrpc.BatchObject.Properties\x12\x12\n\ncollection\x18\x04 \x01(\t\x12\x0e\n\x06tenant\x18\x05 \x01(\t\x1a\xf1\x03\n\nProperties\x12\x33\n\x12non_ref_properties\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\x12O\n\x17single_target_ref_props\x18\x02 \x03(\x0b\x32..weaviategrpc.BatchObject.SingleTargetRefProps\x12M\n\x16multi_target_ref_props\x18\x03 \x03(\x0b\x32-.weaviategrpc.BatchObject.MultiTargetRefProps\x12\x44\n\x17number_array_properties\x18\x04 \x03(\x0b\x32#.weaviategrpc.NumberArrayProperties\x12>\n\x14int_array_properties\x18\x05 \x03(\x0b\x32 .weaviategrpc.IntArrayProperties\x12@\n\x15text_array_properties\x18\x06 \x03(\x0b\x32!.weaviategrpc.TextArrayProperties\x12\x46\n\x18\x62oolean_array_properties\x18\x07 \x03(\x0b\x32$.weaviategrpc.BooleanArrayProperties\x1a\x38\n\x14SingleTargetRefProps\x12\r\n\x05uuids\x18\x01 \x03(\t\x12\x11\n\tprop_name\x18\x02 \x01(\t\x1aR\n\x13MultiTargetRefProps\x12\r\n\x05uuids\x18\x01 \x03(\t\x12\x11\n\tprop_name\x18\x02 \x01(\t\x12\x19\n\x11target_collection\x18\x03 \x01(\t\"\x89\x01\n\x11\x42\x61tchObjectsReply\x12\x0c\n\x04took\x18\x01 \x01(\x02\x12:\n\x06\x65rrors\x18\x02 \x03(\x0b\x32*.weaviategrpc.BatchObjectsReply.BatchError\x1a*\n\nBatchError\x12\r\n\x05index\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v0.batch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_BATCHOBJECTSREQUEST']._serialized_start=78
  _globals['_BATCHOBJECTSREQUEST']._serialized_end=229
  _globals['_BATCHOBJECT']._serialized_start=232
  _globals['_BATCHOBJECT']._serialized_end=1011
  _globals['_BATCHOBJECT_PROPERTIES']._serialized_start=372
  _globals['_BATCHOBJECT_PROPERTIES']._serialized_end=869
  _globals['_BATCHOBJECT_SINGLETARGETREFPROPS']._serialized_start=871
  _globals['_BATCHOBJECT_SINGLETARGETREFPROPS']._serialized_end=927
  _globals['_BATCHOBJECT_MULTITARGETREFPROPS']._serialized_start=929
  _globals['_BATCHOBJECT_MULTITARGETREFPROPS']._serialized_end=1011
  _globals['_BATCHOBJECTSREPLY']._serialized_start=1014
  _globals['_BATCHOBJECTSREPLY']._serialized_end=1151
  _globals['_BATCHOBJECTSREPLY_BATCHERROR']._serialized_start=1109
  _globals['_BATCHOBJECTSREPLY_BATCHERROR']._serialized_end=1151
# @@protoc_insertion_point(module_scope)
