# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v0/weaviate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from v0 from . import batch_pb2 as v0_dot_batch__pb2
from v0 from . import search_get_pb2 as v0_dot_search__get__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11v0/weaviate.proto\x12\x0cweaviategrpc\x1a\x0ev0/batch.proto\x1a\x13v0/search_get.proto2\xa4\x01\n\x08Weaviate\x12\x42\n\x06Search\x12\x1b.weaviategrpc.SearchRequest\x1a\x19.weaviategrpc.SearchReply\"\x00\x12T\n\x0c\x42\x61tchObjects\x12!.weaviategrpc.BatchObjectsRequest\x1a\x1f.weaviategrpc.BatchObjectsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v0.weaviate_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_WEAVIATE']._serialized_start=73
  _globals['_WEAVIATE']._serialized_end=237
# @@protoc_insertion_point(module_scope)
