from typing import List, Optional

from weaviate.connect.v4 import ConnectionAsync
from weaviate.namespaces.base import _NamespacesExecutor
from weaviate.namespaces.models import Namespace

class _NamespacesAsync(_NamespacesExecutor[ConnectionAsync]):
    async def create(self, *, name: str, home_node: Optional[str] = None) -> Namespace: ...
    async def update(self, *, name: str, home_node: str) -> Namespace: ...
    async def get(self, *, name: str) -> Optional[Namespace]: ...
    async def list_all(self) -> List[Namespace]: ...
    async def delete(self, *, name: str) -> None: ...
