from typing import List, Optional

from weaviate.connect.v4 import ConnectionSync
from weaviate.namespaces.base import _NamespacesExecutor
from weaviate.namespaces.models import Namespace

class _Namespaces(_NamespacesExecutor[ConnectionSync]):
    def create(self, *, name: str) -> Namespace: ...
    def get(self, *, name: str) -> Optional[Namespace]: ...
    def list_all(self) -> List[Namespace]: ...
    def delete(self, *, name: str) -> None: ...
